### ISSUE TITLE
[py2] TypeError: 'encoding' is an invalid keyword argument for this function (open)

### ISSUE THREAD

**Issue by pointlessone** [rubik/radon#101]
Hello,

I'm having some issues running Radon master with Python2.

I'm getting this error:

> TypeError: 'encoding' is an invalid keyword argument for this function

With some digging I managed to get this traceback:

```
Traceback (most recent call last):
  File "/usr/bin/radon2", line 11, in <module>
    load_entry_point('radon==1.4.2', 'console_scripts', 'radon')()
  File "/usr/lib/python2.7/site-packages/radon/__init__.py", line 15, in main
    program()
  File "/usr/lib/python2.7/site-packages/mando/core.py", line 125, in __call__
    self.execute(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/mando/core.py", line 121, in execute
    return command(*a)
  File "/usr/lib/python2.7/site-packages/radon/cli/__init__.py", line 64, in cc
    log_result(harvester, json=json, xml=xml, codeclimate=codeclimate)
  File "/usr/lib/python2.7/site-packages/radon/cli/__init__.py", line 187, in log_result
    for msg, args, kwargs in harvester.to_terminal():
  File "/usr/lib/python2.7/site-packages/radon/cli/harvest.py", line 154, in to_terminal
    for name, blocks in self.results:
  File "/usr/lib/python2.7/site-packages/radon/cli/harvest.py", line 84, in caching_iterator
    for t in it:
  File "/usr/lib/python2.7/site-packages/radon/cli/harvest.py", line 67, in run
    with _open(name) as fobj:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/site-packages/radon/cli/tools.py", line 53, in _open
    with open(path, encoding=_encoding) as f:
```

I'm running Radon master (8e1e7fcd14c4da911a95ba910782002745073605) with Python 2.7.13 on Linux.

**Comment by rubik** [comment]
Damn, you are right, thanks for the report

**Comment by pointlessone** [comment]
Cheers!
