### ISSUE TITLE
ERROR: string indices must be integers, not str

### ISSUE THREAD

**Issue by grayaii** [rubik/radon#142]
I'm getting the following error when using radon:

    radon cc  --xml my_repo
    ERROR: string indices must be integers, not str

This happens with python 2 and python 3.
It also happens with the following radon versions (I didn't test earlier than 1.4.2):
1.4.2,1.5.0, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.1, 2.2.0

**Comment by grayaii** [comment]
I was able to get a stack trace:

    Traceback (most recent call last):
      File "/Users/alexgray/.pyenv/versions/2.7.14/lib/python2.7/site-packages/radon/__init__.py", line 15, in main
        program()
      File "/Users/alexgray/.pyenv/versions/2.7.14/lib/python2.7/site-packages/mando/core.py", line 201, in __call__
        return self.execute(sys.argv[1:])
      File "/Users/alexgray/.pyenv/versions/2.7.14/lib/python2.7/site-packages/mando/core.py", line 197, in execute
        return command(*a)
      File "/Users/alexgray/.pyenv/versions/2.7.14/lib/python2.7/site-packages/radon/cli/__init__.py", line 64, in cc
        log_result(harvester, json=json, xml=xml, codeclimate=codeclimate)
      File "/Users/alexgray/.pyenv/versions/2.7.14/lib/python2.7/site-packages/radon/cli/__init__.py", line 184, in log_result
        log(harvester.as_xml(), noformat=True)
      File "/Users/alexgray/.pyenv/versions/2.7.14/lib/python2.7/site-packages/radon/cli/harvest.py", line 144, in as_xml
        return dict_to_xml(self._to_dicts())
      File "/Users/alexgray/.pyenv/versions/2.7.14/lib/python2.7/site-packages/radon/cli/tools.py", line 288, in dict_to_xml
        et.SubElement(metric, 'complexity').text = str(block['complexity'])
    TypeError: string indices must be integers, not str

By adding traceback in init.py:

    import sys
    from radon.cli import program, log_error
    import traceback
    if not sys.argv[1:]:
        sys.argv.append('-h')
    try:
        program()
    except Exception as e:
        print(traceback.format_exc())

I'm gonna keep digging, but at least it's reproducible :)

**Comment by grayaii** [comment]
OK. I found the root cause.  We had a python file that had a typo in it.  Once we fixed the typo, radon finsihed successfully.

**Comment by diresi** [comment]
Oh that's nasty ...

**Comment by diresi** [comment]
I use this patch as a quick workaround:
```
bash-4.2$ diff -Naur venv/lib/python3.7/site-packages/radon/cli/tools.b.py venv/lib/python3.7/site-packages/radon/cli/tools.py
--- venv/lib/python3.7/site-packages/radon/cli/tools.b.py       2019-11-20 14:58:11.856000633 +0100
+++ venv/lib/python3.7/site-packages/radon/cli/tools.py 2019-11-20 14:57:25.527011102 +0100
@@ -303,6 +303,10 @@
     xml.'''
     ccm = et.Element('ccm')
     for filename, blocks in results.items():
+        if "error" in blocks:
+            import logging
+            logging.getLogger(__name__).warning("failed to read %s: %s", filename, blocks["error"])
+            continue
         for block in blocks:
             metric = et.SubElement(ccm, 'metric')
             et.SubElement(metric, 'complexity').text = str(block['complexity'])
```

**Comment by ppi-agray** [comment]
The workaround patch works, but it would be nice to get this fixed.
