### ISSUE TITLE
ERROR: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by kimi-p** [rubik/radon#170]
I'm running `radon hal myfile.py`, but got this: `ERROR: super() takes at least 1 argument (0 given)`. Any idea why? thanks!

OS: macOS Majove 10.14.5
radon==3.0.1

**Comment by rwbogl** [comment]
Are you using Python 2? When I wrote the code for the `hal` option, I forgot to take into account that Python 3's `super()` is not backwards compatible with Python 2.

**Comment by bhrutledge** [comment]
This seems to be an issue with Python 2:

```
$ python2 -m virtualenv venv

$ . venv/bin/activate

$ python --version
Python 2.7.15

$ pip install radon
Successfully installed colorama-0.4.1 configparser-3.7.4 entrypoints-0.3 enum34-1.1.6 flake8-3.7.7 flake8-polyfill-1.0.2 functools32-3.2.3.post2 mando-0.6.4 mccabe-0.6.1 pycodestyle-2.5.0 pyflakes-2.1.1 radon-3.0.1 six-1.12.0 typing-3.6.6

$ touch test.py

$ radon hal test.py
ERROR: super() takes at least 1 argument (0 given)
```

**Comment by bhrutledge** [comment]
@rwbogl Gotcha. Is that something that could be fixed? I'm interested in using this tool to aid a migration from Python 2.

**Comment by rwbogl** [comment]
@bhrutledge It should be a pretty small fix. I'll take a look at it now.

**Comment by rwbogl** [comment]
@bhrutledge PR #172 should fix this problem! You might have to clone the repo rather than use pip until a new version gets pushed out to PyPi.

**Comment by kimi-p** [comment]
yeah the fix works for me. @rwbogl @bhrutledge thanks!
```
pip install git+https://github.com/rwbogl/radon.git
pip install future
```

**Comment by bhrutledge** [comment]
Happy to help. @kimi-p, I would leave this issue open, until the PR is merged (which will close it automatically).

**Comment by rubik** [comment]
@bhrutledge @rwbogl It's merged, I'll push a new version shortly. Thanks @rwbogl!

**Comment by rubik** [comment]
Version 3.0.2 was pushed to PyPI.

**Comment by Holiverh** [comment]
Looks like 3.0.2 is broken sadly, missing the `future` requirement.

```
~ ▶▶▶ vf tmp
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/oliver/.virtualenvs/tempenv-0d0c131172d0d/bin/python2
Also creating executable in /home/oliver/.virtualenvs/tempenv-0d0c131172d0d/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
~
 ⌥ vf tempenv-0d0c131172d0d / 2.7.13 ▶▶▶ pip install radon
   <snip>
Successfully installed colorama-0.4.1 configparser-3.7.4 entrypoints-0.3 enum34-1.1.6 flake8-3.7.7 flake8-polyfill-1.0.2 functools32-3.2.3.post2 mando-0.6.4 mccabe-0.6.1 pycodestyle-2.5.0 pyflakes-2.1.1 radon-3.0.2 six-1.12.0 typing-3.6.6
~
 ⌥ vf tempenv-0d0c131172d0d / 2.7.13 ▶▶▶ radon --version
Traceback (most recent call last):
  File "/home/oliver/.virtualenvs/tempenv-0d0c131172d0d/bin/radon", line 10, in <module>
    sys.exit(main())
  File "/home/oliver/.virtualenvs/tempenv-0d0c131172d0d/local/lib/python2.7/site-packages/radon/__init__.py", line 10, in main
    from radon.cli import program, log_error
  File "/home/oliver/.virtualenvs/tempenv-0d0c131172d0d/local/lib/python2.7/site-packages/radon/cli/__init__.py", line 10, in <module>
    from radon.cli.harvest import CCHarvester, RawHarvester, MIHarvester, HCHarvester
  File "/home/oliver/.virtualenvs/tempenv-0d0c131172d0d/local/lib/python2.7/site-packages/radon/cli/harvest.py", line 3, in <module>
    from builtins import super
ImportError: No module named builtins
~
 ⌥ vf tempenv-0d0c131172d0d / 2.7.13 ▶▶▶ pip install future
Collecting future
Installing collected packages: future
Successfully installed future-0.17.1
~
 ⌥ vf tempenv-0d0c131172d0d / 2.7.13 ▶▶▶ radon --version
3.0.2
```

3.0.1 works _fine_ with the equivalent steps. Looks as if #172 was missing an addition of `future` to `install_requires`?

**Comment by rubik** [comment]
@Holiverh Thanks! It was my fault for not testing it (I don't have Python 2 anymore on my machine, sigh).

**Comment by rubik** [comment]
Version 3.0.3 is on PyPI
