### ISSUE TITLE
halstead error：'dict' object has no attribute 'total'

### ISSUE THREAD

**Issue by wuligaigai** [rubik/radon#176]
I'm sorry to bother you. Recently, I've been using your tools to analyze the halstead complexity of Python code, but when I run radon Hal XX.py,  sometimes an error would happen :'dict'object has no attribute'total'. I don't know what the problem is. Can you answer it?

**Comment by rubik** [comment]
Please provide at least the full traceback, so we can see where the error gets thrown. If possible, also provide your code. Without either one of those, it's very difficult to fix this.

**Comment by apollovy** [comment]
The source I'm getting this is here: https://github.com/kwoodson/ansible-role-yedit/blob/master/tests/test.py

And the full traceback is
```
ERROR:root:'dict' object has no attribute 'total'
Traceback (most recent call last):
  File "/Users/apollov/.pyenv/versions/3.7.3/envs/radon/lib/python3.7/site-packages/radon/__init__.py", line 19, in main
    program()
  File "/Users/apollov/.pyenv/versions/3.7.3/envs/radon/lib/python3.7/site-packages/mando/core.py", line 201, in __call__
    return self.execute(sys.argv[1:])
  File "/Users/apollov/.pyenv/versions/3.7.3/envs/radon/lib/python3.7/site-packages/mando/core.py", line 197, in execute
    return command(*a)
  File "/Users/apollov/.pyenv/versions/3.7.3/envs/radon/lib/python3.7/site-packages/radon/cli/__init__.py", line 255, in hal
    log_result(harvester, json=json, xml=False, stream=stream)
  File "/Users/apollov/.pyenv/versions/3.7.3/envs/radon/lib/python3.7/site-packages/radon/cli/__init__.py", line 316, in log_result
    for msg, h_args, h_kwargs in harvester.to_terminal():
  File "/Users/apollov/.pyenv/versions/3.7.3/envs/radon/lib/python3.7/site-packages/radon/cli/harvest.py", line 340, in to_terminal
    for msg in hal_report_to_terminal(res.total, 0):
AttributeError: 'dict' object has no attribute 'total'
```

**Comment by maramassi** [comment]
I am facing the same problem. Did you manage to solve the problem, Yuri?

**Comment by apollovy** [comment]
> I am facing the same problem. Did you manage to solve the problem, Yuri?

Frankly, I don't remember, it was 3 years ago 😄
