### ISSUE TITLE
If error msg contains a curly bracket, log will fail when attempted to use format

### ISSUE THREAD

**Issue by marcoquerque** [rubik/radon#188]
I have a syntax error in a file that is involves an error message with a curly bracket:

The msg here: https://github.com/rubik/radon/blob/8db8eac6b93aca1eea818060b62350a7cf6a7d36/radon/cli/__init__.py#L353

I imagine msg contains the curly bracket at the format call here:

https://github.com/rubik/radon/blob/8db8eac6b93aca1eea818060b62350a7cf6a7d36/radon/cli/__init__.py#L338

**Comment by rubik** [comment]
Interesting. Can you provide a minimal code sample that shows the error?

**Comment by marcoquerque** [comment]
This is a very simple use case, I imagine there could be others:
```
def not_python_3():
    print "}"
```
python3 raises a syntax error:
```SyntaxError: Missing parentheses in call to 'print'. Did you mean print("}")?```

Radon can't capture the error because while doing so it has its own error:
```tmp.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/radon/__init__.py", line 15, in main
    program()
  File "/usr/local/lib/python3.7/site-packages/mando/core.py", line 201, in __call__
    return self.execute(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/mando/core.py", line 197, in execute
    return command(*a)
  File "/usr/local/lib/python3.7/site-packages/radon/cli/__init__.py", line 119, in cc
    stream=stream)
  File "/usr/local/lib/python3.7/site-packages/radon/cli/__init__.py", line 321, in log_result
    log_error(h_args[0], indent=1)
  File "/usr/local/lib/python3.7/site-packages/radon/cli/__init__.py", line 353, in log_error
    log('{0}{1}ERROR{2}: {3}'.format(BRIGHT, RED, RESET, msg), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/radon/cli/__init__.py", line 338, in log
    m = msg if kwargs.get('noformat', False) else msg.format(*args)
ValueError: Single '}' encountered in format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/radon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/radon/__init__.py", line 17, in main
    log_error(e)
  File "/usr/local/lib/python3.7/site-packages/radon/cli/__init__.py", line 353, in log_error
    log('{0}{1}ERROR{2}: {3}'.format(BRIGHT, RED, RESET, msg), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/radon/cli/__init__.py", line 338, in log
    m = msg if kwargs.get('noformat', False) else msg.format(*args)
ValueError: Single '}' encountered in format string```

**Comment by marcoquerque** [comment]
Generalizing this issue, any error that happens during parsing, that throws an error with a curly bracket in its message, radon is likely to fail instead of capturing that error.
