### ISSUE TITLE
Python 2.7: no module named configparser

### ISSUE THREAD

**Issue by edwinelisia** [rubik/radon#190]
Getting this under python 2.7

```Traceback (most recent call last):
  File "/usr/bin/xenon", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/xenon/__init__.py", line 72, in main
    from xenon.core import analyze
  File "/usr/lib/python2.7/site-packages/xenon/core.py", line 6, in <module>
    from radon.cli import Config
  File "/usr/lib/python2.7/site-packages/radon/cli/__init__.py", line 7, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by rubik** [comment]
Fixed by 4008c9d
