### ISSUE TITLE
Radon unable to calculate metrics for python2 files

### ISSUE THREAD

**Issue by kush96** [rubik/radon#196]
Is there some way possible to calculate cc,raw and halstead metrics for a python2 file when calling radon using python3 . Currently i had the following file

file1.txt

```
print "hello"
```
when i run radon on the above file, i get the following error
```
Traceback (most recent call last):
  File "/Users/singhkus/Blueoptima/Repos/integrator/metrics.bin/python/radon.py", line 94, in <module>
    main()
  File "/Users/singhkus/Blueoptima/Repos/integrator/metrics.bin/python/radon.py", line 57, in main
    dac,fileCycloInfo  = cc_visit(programString)
  File "/Users/singhkus/Blueoptima/Repos/integrator/metrics.bin/python/custom_cc_visitor.py", line 11, in cc_visit
    ast = code2ast(code)
  File "/Users/singhkus/Blueoptima/Repos/integrator/metrics.bin/python/radon/visitors.py", line 32, in code2ast
    return ast.parse(source)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    print "hello"
                ^
```

Is there a work about around this?

**Comment by rubik** [comment]
The Python code is parsed with the Python version you are running Radon in. If you run Radon with Python 3, it will only parse Python 3 files. So you should run Radon with Python 2.7.
