### ISSUE TITLE
Syntax error with code ending with \

### ISSUE THREAD

**Issue by ghazpar** [rubik/radon#204]
If I run the following code:
```python
import radon.raw

source = 'print()\\'
print(source)

radon.raw.analyze(source)
```
A syntax error is raised:
```python
Traceback (most recent call last):

  File "/opt/miniconda/lib/python3.7/site-packages/radon/raw.py", line 210, in analyze
    tokens, parsed_lines = _get_all_tokens(line, lines)

  File "/opt/miniconda/lib/python3.7/site-packages/radon/raw.py", line 117, in _get_all_tokens
    next_line = next(lines)

StopIteration


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/miniconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-40-a4842f4d775e>", line 6, in <module>
    radon.raw.analyze(source)

  File "/opt/miniconda/lib/python3.7/site-packages/radon/raw.py", line 212, in analyze
    raise SyntaxError('SyntaxError at line: {0}'.format(lineno))

  File "<string>", line unknown
SyntaxError: SyntaxError at line: 1
```

The source code in `source` is certainly bad code style, but it is not a syntax error per se, at least not for Python 3.

I have this bug for radon 4.3.2 and Python 3.7.1.

**Comment by rubik** [comment]
Hi Marc. The source code in the string is definitely invalid. You can verify by putting the same code in a file and executing it with Python directly:

```shell
$ cat a.py
print()\\
$ python a.py
  File "/home/miki/a.py", line 1
    print()\\
SyntaxError: unexpected character after line continuation character
```
