### ISSUE TITLE
Revert use of compatible release operator in requirements version specification 

### ISSUE THREAD

**Issue by andornaut** [rubik/radon#83]
Attempting to install radon 1.3.1 using pip 1.5.6 fails:
```
pushd $(mktemp -d) >/dev/null
virtualenv -q v
source v/bin/activate
pip install -qU pip==1.5.6
pip install -q radon==1.3.1
Exception:
Traceback (most recent call last):
  File "/tmp/tmp.qEH0a9gYbt/v/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/tmp/tmp.qEH0a9gYbt/v/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/tmp/tmp.qEH0a9gYbt/v/local/lib/python2.7/site-packages/pip/req.py", line 1265, in prepare_files
    req_to_install.extras):
  File "/tmp/tmp.qEH0a9gYbt/v/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/tmp/tmp.qEH0a9gYbt/v/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/tmp/tmp.qEH0a9gYbt/v/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/tmp/tmp.qEH0a9gYbt/v/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 45, in <lambda>
    next = lambda o: o.next()
  File "/tmp/tmp.qEH0a9gYbt/v/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/tmp/tmp.qEH0a9gYbt/v/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'colorama ~=0.3', 'at', ' ~=0.3')

Storing debug log for failure in /home/andornaut/.pip/pip.log
```
Whereas attempting to install radon 1.3.0 using pip 1.5.6 succeeds:
```
pushd $(mktemp -d) >/dev/null
virtualenv -q v
source v/bin/activate
pip install -qU pip==1.5.6
pip install -q radon==1.3.0
```
The error in the first example is caused by the use of the [compatible release operator](https://github.com/rubik/radon/commit/0572ba6f2c8ceee668674e376237dc91475317b2) in the "install_requires" argument to ``setuptools.setup()``. Instead, the compatible releases can be specified using ``'mando>=0.3,<0.4'``, which is better supported by older versions of pip.

Although both versions of radon can be installed successfully using pip 8.1.1, it'd be nice if radon could be installed using older versions of pip.

**Comment by rubik** [comment]
Thank you for your report. I'm curious: could you describe a scenario in which one must use pip 1.5.6? Since pip can upgrade itself, it does not seem like a big deal. However, I'm open to changing the version specification if this reveals to be necessary.

**Comment by andornaut** [comment]
Pip can usually be upgraded, sure, but it'd be nice if this project did not require that a recent version be installed.

**Comment by rubik** [comment]
Fair enough. I pushed version 1.3.2 to PyPI.
