### ISSUE TITLE
Crash with Flake8 3.0.1

### ISSUE THREAD

**Issue by 9seconds** [rubik/radon#92]
Hi,

I've installed radon (1.4.0) with Flake8 3.0.1 and got following error on flake8 execution:

```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/qqq/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/flake8/main/application.py", line 299, in _run
    self.initialize(argv)
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/flake8/main/application.py", line 290, in initialize
    self.register_plugin_options()
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/flake8/main/application.py", line 150, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/flake8/plugins/manager.py", line 451, in register_options
    list(self.manager.map(register_and_enable))
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/flake8/plugins/manager.py", line 261, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/flake8/plugins/manager.py", line 447, in register_and_enable
    call_register_options(plugin)
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/flake8/plugins/manager.py", line 357, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/flake8/plugins/manager.py", line 207, in register_options
    add_options(optmanager)
  File "/home/ubuntu/.pyenv/versions/qqq/lib/python3.5/site-packages/radon/complexity.py", line 132, in add_options
    parser.config_options.append('radon-max-cc')
AttributeError: 'OptionManager' object has no attribute 'config_options'
```

I guess, this issue is similar to https://github.com/PyCQA/flake8-import-order/issues/79

**Comment by sigmavirus24** [comment]
See also: http://flake8.pycqa.org/en/latest/plugin-development/cross-compatibility.html

**Comment by rubik** [comment]
Version 1.4.1 pushed to PyPI. I've tested it on Flake8 2.x and 3.x, but let me know if there are other problems.
